baseURL: "https://profile.gurusabarish.tech"
languageCode: "en-us"
title: "bomaindragunawan"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Boma Indra Gunawan"
  profession: "Application Middleware Engineer"
  github: "https://github.com/bomaindragunawan"
  linkedin: "https://www.linkedin.com/in/boma-indra-gunawan-a80554186/"
  twitter: "https://twitter.com/"
  instagram: "https://instagram.com/bomaindragunawan"
  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Boma Indra Gunawan, a passionate Artificial Intelligence, DevOps and Web Development."
  descripe_l2_person: "I'm currently working as Application Middleware Engineer at IBM. You can find my works [here](#projects)"
  skills:
    - name: Python
      percentage: 90
    - name: Math Algorithms
      percentage: 85
    - name: Backend
      percentage: 80
    - name: DevOps
      percentage: 80

  # Experience
  disable_experience: false
  experience:
    - company: "Kementrian Keuangan"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Network Engineer - Internship"
      startdate: August 2019
      enddate: September 2019
      featuredpoints:
        - point: Configure network.
        - point: Created a architure network.
    - company: "BATS International"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "AI Engineer - Internship"
      startdate: February 2019
      enddate: April 2019
      featuredpoints:
        - point:  Created a Image Recognition for Tax Report.
        - point: The tools help for data entry running the job quickly.
    - company: "IBM"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Application Engineer"
      startdate: December 2019
      enddate: now
      featuredpoints:
        - point: Handling system middleware for telco.
        - point: Analyse and resolve the problem.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Gunadarma university"
      startedyear: "2015"
      graduation: "2019"
    - degree: "Artificial Intelligence"
      branch: "Digital Talent Scholarship"
      university: "Example university"
      startedyear: "2019"
      graduation: "2019"

  # Projects
  disable_projects: false
  projects:
    - name: "QR Payment Application based on Android"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"
    - name: "Credit Score Prediction by Applying Naive Bayes Algorithm in Machine Learning"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"
    - name: "Music Recommendation Based of Face Expression Detection"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"   
  
  # Achievements
  disable_achievements: True
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "bomaindragunawan@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
